/*
 * OreoHelp.c
 *
 */


#define INCL_VIO
#define INCL_DOS
#include <os2.h>
#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include "GnuMem.h"
#include "GnuScr.h"
#include "GnuKbd.h"


char  szStar[] = "-\\|/";


USHORT _cdecl Help (USHORT c)
   {
   PGW    pgw1, pgw2;
   PMET   pmet;
   USHORT z=0;

   /*--- Main Window ---*/
   ScrSaveCursor (FALSE);
   pmet = ScrGetMetrics ();

   pgw1 = GnuCreateWin (11, 50, NULL);
   pgw1->pszHeader = "[Help]";
   pgw1->pszFooter = "[<ESC> to Exit]";
   GnuPaintBorder (pgw1);
   GnuPaintBig (pgw1, 1, 5, 7, 49, 0, 0,
               "\\@01<F1>\\@00 ..... About\n"
               "\\@01<F2>\\@00 ..... General Help\n"
               "\\@01<F3>\\@00 ..... Command line arguments\n"
               "\\@01<F4>\\@00 ..... Loading and Saving\n"
               "\\@01<F5>\\@00 ..... Changing Planets / Fleets \n"
               "\\@01<F6>\\@00 ..... Changing Technology Advances\n"
               "\\@01<F7>\\@00 ..... Other commands");

   while (TRUE)
      {
      switch (c = KeyChoose ("1234567AGCLPTO\x1B", "\x3b\x3c\x3d\x3e\x3f\x40\x41"))
         {
         case 0x13b:
         case '1':
         case 'A':
            /*--- About Window ---*/
            pgw2 = GnuCreateWin (13, 44, NULL);
            pgw2->pszHeader = "[Help - About]";
            pgw2->pszFooter = "[<ESC> to Exit]";
            GnuPaintBorder (pgw2);
            GnuPaint (pgw2, 1,  0,  3, 0, "Masters of Orion");
            GnuPaint (pgw2, 2,  0,  3, 0, "Save File Editor");
            GnuPaint (pgw2, 3,  0,  3, 0, "v1.1  - OS/2 & DOS");
            GnuPaint (pgw2, 5,  0,  3, 0, "Craig Fitzgerald");
            GnuPaint (pgw2, 6,  0,  3, 0, "2900 SW 2nd Ct.");
            GnuPaint (pgw2, 7,  0,  3, 0, "Gainesville, Fl. 32608");
            GnuPaint (pgw2, 9,  0,  3, 0, "Feel Free to send money");
            KeyClearBuff ();
            while (!k_kbhit ())
               {
               z = (z+1) % 4;
               GnuPaintNChar (pgw2, 1, 3,  0, 1, szStar[z], 1);
               GnuPaintNChar (pgw2, 1, 38, 0, 1, szStar[z], 1);
               DosSleep (30);
               }
            GnuDestroyWin (pgw2);
            break;

         case 0x13c:
         case '2':
         case 'G':
            /*--- General Help ---*/
            GnuMsgBox ("[Help - General Help]", "[<ESC> to Exit]", "\x1B\x0D",
               "This program modifies save files generated by Masters of ORION by MicroProse.  "
               "This program can be used to edit planet attributes, fleet sizes, and technology "
               "advances.  Its use is similar "
               "to that of a spread sheet in that you can scroll horizontally or "
               "vertically, and has an active cell that you can edit.  This program "
               "will edit save files from the original release (v1.0) and from the "
               "patched version (v1.2).  You may set the number of screen lines the "
               "program is to use via command line arguments.  Type OREO /? to see "
               "a brief description of these arguments.  And finally, this program is "
               "a bound application, which means it also runs in OS/2 ");
            break;

         case 0x13d:
         case '3':
         case 'C':
            /*--- Command line arguments ---*/
            GnuMsgBox ("[Help - Command Line Arguments]", "[<ESC> to Exit]", "\x1B\x0D",
               " OREO [options] [savefile]\n\n"
               " [options]  Are 0 or more of:\n"
               "  /Lines=# .. Set Number of screen lines (25, 28, 50)\n"
               "  /V12 ...... Save files are from MOO ver 1.2 (default is\n"
               "              auto detect)\n"
               "  /V10 ...... Save files are from MOO ver 1.0\n"
               "  /? ........ List of options similar to this screen.\n\n"
               " [savefile]  If specified is loaded immediately.  Masters\n"
               "              of ORION save files are of the form save?.GAM\n"
               "              where ? is 1 through 7.\n");
            break;

         case 0x13e:
         case '4':
         case 'L':
            /*--- Loading and saving ---*/
            GnuMsgBox ("[Help - Loading and Saving]", "[<ESC> to Exit]", "\x1B\x0D",
               "Load a save file using the <F2> key.  Select a drive to change to "
               "that drive, or select a directory to change to that directory and "
               "hit <enter>.  only files with a .GAM OR .BAK extention are viewed. "
               "Select the file you want to load and hit enter.\n"
               "Save a file using the <F3> key.  You will be prompted to make sure "
               "you want to save.");
            break;

         case 0x13f:
         case '5':
         case 'P':
            /*--- Changing planet attributes and fleet sizes ---*/
            GnuMsgBox ("[Help - Changing Planets / Fleets]", "[<ESC> to Exit]", "\x1B\x0D",
               "Select the attribute you wish to change using the arrow keys and hit "
               "<Enter>.  For planet names, simply edit the name in place.  For numeric "
               "fields, enter the new number.  For other fields, a list will pop up "
               "and you can select which choice you want.  As an alternative, you can "
               "select the field you wish to change and hit <+> to increment or <-> to "
               "decrement the field value (note this does not work for the planet name field). "
               "Changes are not kept until you save the file via <F3>. ");
            break;

         case 0x140:
         case '6':
         case 'T':
            /*--- Changing Technology ---*/
            GnuMsgBox ("[Help - Changing Technology Advances]", "[<ESC> to Exit]", "\x1B\x0D",
               "To change the technology of the race that owns the currently selected planet type <Alt-T>. "
               "This will pop up a window showing the number of advancements achieved for "
               "each technology for each race.  Simply change any number you want.");
            break;

         case 0x141:
         case '7':
         case 'O':
            /*--- Other Commands ---*/
            GnuMsgBox ("[Help - Other Commands]", "[<ESC> to Exit]", "\x1B\x0D",
               "Below is a list of the other command keys available "
               "when editing save files.\n\n"
               "\\@01<Alt-T>\\@00....... Edit Technology Advances.\n"
               "\\@01<Home>\\@00........ Jump to the first planet in the list.\n"
               "\\@01<End>\\@00......... Jump to the last planet in the list.\n"
               "\\@01<Ctl-Left>\\@00.... Jump to the Left of the screen.\n"
               "\\@01<Ctl-Right>\\@00... Jump to the Right of the screen.\n"
               "\\@01<Alt-S>\\@00....... Sort planets by the current column.\n"
               "\\@01<+>\\@00........... Increment the value of the selected cell.\n"
               "\\@01<->\\@00........... Decrement the value of the selected cell.\n"
               "\\@01<Alt-P>\\@00 ...... Propagate the value of the current cell down.\n"
               "\\@01<Alt-R>\\@00 ...... Reverse sort order.\n"
               "\\@01<Ctl-R>\\@00....... Refresh Screen.\n"
               "\\@01<Alt-H>\\@00....... Edit the current planet in hex mode.\n"
               "\\@01<Alt-M>\\@00....... Maximize all fundung levels for this planet.\n"
               "\\@01<Ctl-Up>\\@00...... Move to top.\n"
               "\\@01<Ctl-Dn>\\@00...... Move to bottom.\n"
               "\\@01<Ctl-F1>\\@00...... Record key strokes (also stops recording).\n"
               "\\@01<Ctl-F2>\\@00...... Play back recorded key strokes.\n");
            break;

         case '\x1B':
            GnuDestroyWin (pgw1);
            ScrRestoreCursor ();
            return 0;
         }
      }
   return 0;
   }
